stages:
  - autotests

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .venv

autotests_linux:
  stage: autotests
  image: python:3.12
  script:
    - python -m venv .venv
    - .venv/bin/pip install -U pip
    - .venv/bin/pip install -U tortoise-orm aiogram fastapi rich ruff pyright
    - tests=true .venv/bin/python galaxy_backend

